name: flutter_google_places_autocomplete
description: Google places autocomplete widgets for flutter.
version: 0.0.5
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/flutter_google_places_autocomplete

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_webservice: "^0.0.3"
  rxdart: ^0.18.1

dev_dependencies:
  test: ^0.12.0
